const statusCodes = {
  [0]: {code: 0,
        name: 'Success',
        text: 'The message was successfully accepted for delivery by Nexmo.'},
  [1]: {code: 1,
        name: 'Throttled',
        text: 'You have exceeded the submission capacity allowed on this account. Please wait and retry.'},
  [2]: {code: 2,
        name: 'Missing params',
        text: 'Your request is incomplete and missing some mandatory parameters.'},
  [3]: {code: 3,
        name: 'Invalid params',
        text: 'The value of one or more parameters is invalid.'},
  [4]: {code: 4,
        name: 'Invalid credentials',
        text: 'The api_key / api_secret you supplied is either invalid or disabled.'},
  [5]: {code: 5,
        name: 'Internal error',
        text: 'There was an error processing your request in the Platform.'},
  [6]: {code: 6,
        name: 'Invalid message',
        text: 'The Platform was unable to process your request. \
For example, due to an unrecognized prefix for the phone number.'},
  [7]: {code: 7,
        name: 'Number barred',
        text: 'The number you are trying to submit to is blacklisted and may not receive messages.'},
  [8]: {code: 8,
        name: 'Partner account barred',
        text: 'The api_key you supplied is for an account that has been barred from submitting messages.'},
  [9]: {code: 9,
        name: 'Partner quota exceeded',
        text: 'Your pre-paid account does not have sufficient credit to process this message.'},
  [11]: {code: 11,
        name: 'Account not enabled for REST',
        text: 'This account is not provisioned for REST submission, you should use SMPP instead.'},
  [12]: {code: 12,
        name: 'Message too long',
        text: 'The length of udh and body was greater than 140 octets for a binary type SMS request.'},
  [13]: {code: 13,
        name: 'Communication Failed',
        text: 'Message was not submitted because there was a communication failure.'},
  [14]: {code: 14,
        name: 'Invalid Signature',
        text: 'Message was not submitted due to a verification failure in the submitted signature.'},
  [15]: {code: 15,
        name: 'Invalid sender address',
        text: 'Due to local regulations, the SenderID you set in from in the request was not accepted. \
Please check the Global messaging section.'},
  [16]: {code: 16,
        name: 'Invalid TTL',
        text: 'The value of ttl in your request was invalid.'},
  [19]: {code: 19,
        name: 'Facility not allowed',
        text: 'Your request makes use of a facility that is not enabled on your account.'},
  [20]: {code: 20,
        name: 'Invalid Message class',
        text: 'The value of message-class in your request was out of range. \
Possible values are from 0 to 3 inclusive.'},
  [23]: {code: 23,
        name: 'Bad callback :: Missing Protocol',
        text: 'You did not include https in the URL you set in callback.'},
  [29]: {code: 29,
        name: 'Non White-listed Destination',
        text: 'The phone number you set in to is not in your pre-approved destination list. \
To send messages to this phone number, add it using Dashboard.'},
  // The following response codes are for 2FA and Campaign Subscription Management only.
  [101]: {code: 101,
          name: 'RESPONSE_INVALID_ACCOUNT_CAMPAIGN',
          text: 'The following response codes are for 2FA only.'},
  [102]: {code: 102,
          name: 'RESPONSE_MSISDN_OPTED_OUT_FOR_CAMPAIGN',
          text: 'You tried to send a message to a destination number that has opted out of your program.'},
  // The following response codes are for Campaign Subscription Management only.
  //[102]: {code: 102, name: 'RESPONSE_INVALID_CAMPAIGN_SHORTCODE'},
  //[103]: {code: 103, name: 'RESPONSE_INVALID_MSISDN'},
};

export default statusCodes;
